### PR TITLE
Changed default $attribute value to be taken from behavior instance.

### PR DESCRIPTION
**Pull request by hector-del-rio**
Argument $attribute can be retrieved from behavior’s instance.

### CODE REVIEW

**Comment by hector-del-rio** [comment]
I realised that $attribute argument is necessary when you have more than one instance of these behaviors for the same model. 

I will modify it so that unless $attribute is specified it returns the behavior instance attribute.

**Comment by hector-del-rio** [comment]
The thumbs were not being redone after saving the model. I had to remove [this condition](https://github.com/hector-del-rio/yii2-upload-behavior/commit/584ff117442fdf926d111d89fc15f7718ee2e93c#diff-01bc4daa63ef5d3d9db8f261bf91d02dL141).

**Comment by russianlagman** [comment]
Why have you added $attribute to resolvePath? That method is supposed to be ran inside of the behavior and behavior instance already know its attribute.

**Comment by hector-del-rio** [comment]
The function is ```public``` so I thought it made sense to have it in case you want to use it from outside the behavior. It could also be declared as ```protected```or ```private``` and remove $attribute.

What do you think about it?

**Comment by russianlagman** [comment]
Its public for debugging purposes. As you can obtain access to the behavior instance, you can always play with it's path resolver... I think that part of the code should be kept as it was.

**Comment by hector-del-rio** [comment]
Well, I can change that back. But you realise that you can still use ```resolvePath``` function the same way than before, right? it defaults to the behavior's instance $attribute value...

**Pull request closed without merging**
